# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eb74dd253c6ceb715440538c613d93dfa611cc9c22b0ccb57eb882cf842b62b649b42dfeb7f2d9801a22e1a648875d68dd7e619026afd261a78e87e0ba2ab83

test:
  secret_key_base: bb2a34990f859ccc585883ad2ac2d86663d8b4c8418d1aea275f2d53d00d095372260f13037e8a10797d0da8807172be4959b29b2a71450826f58badbd6cb6da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
